# -*- coding: utf-8 -*-
"""Association Rule.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O13lT2IN95bCXljOqHJ_saSvD828rN2j
"""

pip install apyori

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from apyori import apriori

data = pd.read_csv("/content/lulus4tahun.csv", sep = ",", header=None)
data =  data.drop([0])
data = data.drop([0], axis=1)
data

records = []
for i in range(0, 770):
    records.append([str(data.values[i,j]) for j in range(0, 4)])

association_rules = apriori(records, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=2)
association_results = list(association_rules)
print(association_results)

print(len(association_results))
print(association_results[0])

for item in association_results:

    pair = item[0] 
    items = [x for x in pair]
    print("Rule: " + items[0] + " -> " + items[1])

    #second index of the inner list
    print("Support: " + str(item[1]))

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("=====================================")

data = pd.read_csv("/content/hubungan1.csv", sep = ";", header=None, usecols=([7,8,9,10]))
data =  data.drop([0])
data

records = []
for i in range(0, 7053):
    records.append([str(data.values[i,j]) for j in range(0, 4)])
records

association_rules = apriori(records, min_support=0.0045, min_confidence=0.2, min_lift=3, min_length=2)
association_results = list(association_rules)
print(association_results)

print(len(association_results))
print(association_results[0])

for item in association_results:

    pair = item[0] 
    items = [x for x in pair]
    print("Rule: " + items[0] + " -> " + items[1])

    #second index of the inner list
    print("Support: " + str(item[1]))

    print("Confidence: " + str(item[2][0][2]))
    print("Lift: " + str(item[2][0][3]))
    print("=====================================")